sudo: false
language: java
services: docker
cache:
  directories:
  - "$HOME/.cache"

install: true
script:
  - mvn clean package site -B -V

script:
  - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$TRAVIS_COMMIT

notifications:
  email:
    recipients:
      - $EMAIL
    on_success: never
    on_failure: always